// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FluentCodeMetrics.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Calcular Acoplamento Aferente (Ca)")]
    public partial class CalcularAcoplamentoAferenteCaFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AfferentCoupling.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Calcular Acoplamento Aferente (Ca)", "\r\nAcomplamento Aferente é uma métrica que indica a quantidade\r\nde tipos que refer" +
                    "enciam um determinado tipo.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Calcular Acoplamento Aferente para um tipo")]
        [NUnit.Framework.TestCaseAttribute("Samples.Ca.Foo", "1", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Samples.Ca.FooCalculator", "0", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Samples.Ca.FooException", "2", new string[0])]
        public virtual void CalcularAcoplamentoAferenteParaUmTipo(string tipo, string ca, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calcular Acoplamento Aferente para um tipo", exampleTags);
#line 8
 this.ScenarioSetup(scenarioInfo);
#line 9
  testRunner.Given(string.Format("que tenho um {0}", tipo));
#line 10
  testRunner.When("desejo obter seu acoplamento aferente");
#line 11
  testRunner.Then(string.Format("obtenho {0}", ca));
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
